### ISSUE TITLE
Version problems and donate

### ISSUE THREAD

**Issue by userkilled** [CuteCubed/Arionum-Android#1]
In version 1.53, it seems, nothing works at all, only the miner displays something. But in the version from FDroid there works the display of balance and transaction history (but it does not always work stably), the miner does not work. Sending transactions doesn't work anywhere at all.
By the way, has Your donate wallet address changed?

**Comment by CuteCubed** [comment]
Hi userkilled,

The problems you stated belong to the old arionum app which git repository is located here:
https://github.com/CuteCubed/Arionum-Wallet-Android

As for the new app the goal is to get a refurbished and user friendly app up and running again. 
The bugs or disfunctionality of the old app should also be fixed.

There are going to be pre-built binaries once the repository / project gets started properly.
